### ISSUE TITLE
Could you release your dataset and pre-trained models for reproducing your work?

### ISSUE THREAD

**Issue by zhoufengfan** [CGCL-codes/AMT-GAN#1]
Congratulations on the acceptance of this work for CVPR.

We appreciate the work and would like to reproduce the results in the paper. However, the dataset used in the paper is selected from the public dataset by you. It's hard for us to reproduce the results in the paper without the dataset you have used. Could you release your dataset and pre-trained models for reproducing your work?

Thanks a lot.

**Comment by SheltonLiu-N** [comment]
Thanks for your interest！
As we are working on submissions of another conference recently and temporarily understaffed, the codes for reproducing are still in sorting. But they will be released soon (in May 2022 at the latest). And we will also release the checkpoints  (as well as the dataset)  for everyone‘s convenience.

**Comment by samuel930930** [comment]
I have tried to reproduce the results and observe that the given test images from the subset of the CelebA-HQ dataset are 100 images in total. However, according to the paper, it should include 1000 images. Could you upload the full 1000 image subset? Thank you.
