### ISSUE TITLE
What's the `gamma` value of TIP-IM you have set for evaluating the performance of TIP-IM?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [CGCL-codes/AMT-GAN#10]
Hi, the `gamma` value of TIP-IM can affect the performance of TIP-IM a lot.
Could you tell us what's the `gamma` value of TIP-IM you have set for evaluating the performance of TIP-IM?
Thanks and regards.

**Comment by SheltonLiu-N** [comment]
Hi GeorgeCarpenter,
We set the `gamma=5*10-4`.
