### ISSUE TITLE
hello, could please provide code for test image quality?

### ISSUE THREAD

**Issue by yuxu915** [CGCL-codes/AMT-GAN#13]
Hi! Thanks for your great work, and make it open source!
When I test the "FID", "PSNR" and "SSIM",  I find that the results are different from the paper. Could please provide your source testing code? I would like to check if we have different experiment settings.
Thanks again!

**Comment by SheltonLiu-N** [comment]
Hi,
We use [scikit-image](https://github.com/scikit-image/scikit-image) to test PSNR and SSIM, and we use [clean-fid](https://github.com/GaParmar/clean-fid) to test FID.
