### ISSUE TITLE
Have the MI-FGSM, TI-DIM, and TIP-IM in the paper used the ensemble attack strategy, and are the maximum perturbation of PGD, MI-FGSM, TI-DIM, and TIP-IM all 16/255 under the L Infinity distance?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [CGCL-codes/AMT-GAN#14]
Hi, we appreciate the work. However, we have 2 questions about the baseline of Tab.1 in the paper.

1. Have the MI-FGSM, TI-DIM, and TIP-IM in the paper used the ensemble attack strategy?
2. Are the maximum perturbation of PGD, MI-FGSM, TI-DIM, and TIP-IM all 16/255 under the L Infinity Distance?

Hope for your response.
Thanks.

**Comment by SheltonLiu-N** [comment]
Hi,
1.No, because one of the baselines (TIP-IM) uses a target list to calculate the best target identity, using the ensemble strategy will make it hard to apply (please refer to their paper). 
2. Yes.

**Comment by GeorgeCarpenter** [comment]
Thanks for your response. We hope that you could answer the following questions for further clarification.

1. Is there no ensemble attack strategy used in MI-FGSM, TI-DIM, and TIP-IM in the Tab.1 of the paper?
2. Does the maximum perturbation 16/255 means that the maximum perturbation is 16 when the range of the value of the images is [0, 255]?

**Comment by SheltonLiu-N** [comment]
1. Yes.
2. Yes.
