### ISSUE TITLE
 Could you provide the image `pairs` you have used for reproducing the result in Table.1 of the paper?

### ISSUE THREAD

**Issue by yuuma002** [CGCL-codes/AMT-GAN#15]
Hello, thanks for providing the dataset that you have used. Usually, the adversarial attack against FR is performed in a list of `(source, target)` pairs. However, the image pairs used in the experiment in Table.1 are unknown to us, which hinders us from producing the results in the Table. 1.

Could you provide the image `pairs` you have used for reproducing the result in Table.1 of the paper?

**Comment by SheltonLiu-N** [comment]
Hi,
Here are the identities we used for evaluating the AMT-GAN.
[pair.zip](https://github.com/CGCL-codes/AMT-GAN/files/8915163/pair.zip)
