### ISSUE TITLE
About multi-GPU training models

### ISSUE THREAD

**Issue by godHhh** [CGCL-codes/AMT-GAN#17]
Hello, I have two 3080ti, direct run will be out of momeny, where should I change the code please?

**Comment by SheltonLiu-N** [comment]
Hi, 
You can change the settings of the `purifier`  to reduce memory usage. For example, in backbone/solver.py, Line 28, change `self.H = net.H_RRDB(nb=4)` to `self.H = net.H_RRDB(nb=3)` or lower. 
Sorry, we didn't develop the multi-GPU version, maybe you can refer to [PSGAN](https://github.com/wtjiang98/PSGAN).
