### ISSUE TITLE
attack success rate seems different from paper

### ISSUE THREAD

**Issue by yuxu915** [CGCL-codes/AMT-GAN#18]
hi, when I try to reproduce your results in Table 1, results seems different from that in paper.
For example, using **AMT-GAN/test.py**, I try to calculate ASR of **clean** image in CelebA-HQ,  attacking ir152, the results are 0.02,0.019,0.017,0.049, while in paper it's 3.80. The corresponding test image IDs are: 008793, 047073, 055622, 166607.
I wonder if I miss something.
Thanks!

**Comment by SheltonLiu-N** [comment]
Hi,
In the current repository of AMT-GAN, we have added an additional loss in the cycle reconstruction path (See backbone/solver.py Line312-313, Line393-394). This will make the AMT-GAN generate more stable and natural face images (FID degrades from 34 (in our official paper) to 27). As a trade-off, it will slightly affect the attack strength. If you want to have a better ASR or just want to reproduce the results, delete `self.LPIPS(fake_A, image_s), self.LPIPS(fake_B, image_r)` in Line312-313, `self.LPIPS(purified_A, image_s), self.LPIPS(purified_B, image_r)` in Line393-394.

**Comment by Werty18** [comment]
Hi, thanks for clearing this. There is LPIPS loss on page-6 (eq. 11) of the paper. Have you used it for visual results in the paper (in Fig. 4)? and remove it during calculation of ASR?
