### ISSUE TITLE
Questions about the test set 1000 images from CelebA-HQ dataset

### ISSUE THREAD

**Issue by samuel930930** [CGCL-codes/AMT-GAN#2]
I have tried to reproduce the results and observe that the given test images from the subset of the CelebA-HQ dataset are 100 images in total. However, according to the paper, it should include 1000 images. Could you upload the full 1000 image subset? Thank you.

**Comment by SheltonLiu-N** [comment]
Thanks for your interest！
We have renewed the demo test dataset (100 pics to 1000) for a broader evaluation, check it out! ^ ^

**Comment by samuel930930** [comment]
Thank you!
