### ISSUE TITLE
Some inconsistency between the paper and the repo

### ISSUE THREAD

**Issue by GeorgeCarpenter** [CGCL-codes/AMT-GAN#4]
1. The inconsistency of the number of makeup and non-makeup images
The paper wrote:
```Following [2, 19], the Makeup Transfer (MT) dataset [23] is used as the training dataset, which consists of 1115 non-makeup images and 2719 makeup images.```
However, there are 1109 non-makeup images and 2709 makeup images in the dataset you have provided.
2. The inconsistency of the number of the  target identity
The paper wrote:
```We divide all the test images into 4 groups and aim images in each group to the same target identity```
However, there is only 1 one target image you have provided.

Please provide the correct data to reproduce the paper.
Thanks a lot.

**Comment by SheltonLiu-N** [comment]
Sorry for replying late,
1. We have rechecked the `asset` we upload and find there are 1115 non-makeup images and 2719 makeup images in `assets\datasets\MT-dataset\images`. Please try to re-download it. And if you still find some images missing, please inform us.
2. The provided target identity is aligned with the checkpoints we shared, here are the identities we used for evaluating the AMT-GAN.
[pair.zip](https://github.com/CGCL-codes/AMT-GAN/files/8915163/pair.zip)

**Comment by GeorgeCarpenter** [comment]
Hi, have you used the images in the `test` folder of the `pair.zip` for evaluation?

**Comment by SheltonLiu-N** [comment]
Yes,
