### ISSUE TITLE
Does the trained AMT-GAN generator can only attack a single target identity?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [CGCL-codes/AMT-GAN#5]
After training an AMT-GAN model, we are gonna use the trained generator to generate the AXs.  We doubt whether the generator can only attack a single target identity. There are 4 target identities in the paper. Does it mean you have trained 4 different generators?

Hope for your response.

Thanks.

**Comment by SheltonLiu-N** [comment]
Hi,
Yes, the AMT-GAN trained on one single target identity can only attack one single identity. And we trained 4 different generators (in fact, for attacking different target models, we trained 4(identities)*4(FR models) generators) for attacking 4 target identities in the paper. 
How to make GAN extract the information of the target image is promising but challenging, it will be amazing to accomplish this, for example: `G(X_oringnal, R_reference, T_target) = X_adversarial`
