### ISSUE TITLE
Can we feed the facenet model in the repo with the image whose size is (112, 112)?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [CGCL-codes/AMT-GAN#7]
We found that the sizes of the input images of the face recognition models in the repo are (112, 112) except for the facenet model. 

Could you tell us can we feed the facenet model in the repo with the image whose size is (112, 112)?

Thanks.

**Comment by SheltonLiu-N** [comment]
Yes, you can feed facenet with image size (112, 112).  
For the repo, we set it (160, 160) in order to keep aligned with [Adv-Makeup](https://github.com/TencentYoutuResearch/Adv-Makeup) for comparison. In fact, you can get better results if you set image size = (112, 112).

**Comment by GeorgeCarpenter** [comment]
Are the pre-trained face recognition models the same as Adv-Makeup's?

**Comment by SheltonLiu-N** [comment]
Yes, we use the same checkpoints they shared in their repository.
You can also use [FaceX-Zoo](https://github.com/JDAI-CV/FaceX-Zoo) if you want to attack more FR models.
