### ISSUE TITLE
What's the calculation method of the SSIM value in the paper?

### ISSUE THREAD

**Issue by zhoufengfan** [CGCL-codes/AMT-GAN#9]
Hi! We found that the SSIM values which were calculated by `skimage.metrics.structural_similarity` and `torchmetrics.functional.structural_similarity_index_measure` are different(see the example below).
Could you tell us what's the calculation method of the SSIM value in the paper?
Example:
![Example](https://user-images.githubusercontent.com/67182587/176328534-ec4ed26f-76f1-4e83-95ce-99b01ccb8121.png)

**Comment by SheltonLiu-N** [comment]
Hi, zhoufengfan
We use skimage.metrics.structural_similarity for evaluation.
